language: scala

sudo: false

scala:
- 2.11.11
- 2.12.3

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++${TRAVIS_SCALA_VERSION}!" checkGenerate test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)

env:
  global:
  - secure: "XgZOQXCbd3CgT2F9xsFtDNDb1M2ZgxzIa3Awd48aMUjP2yS/gRExjahlgXeBmTWOleRo810mh4N90q0gLy670Ois4/d/l+06XLu2Aa3gDIbWfkCCkZdbgQ/4eEsKzfBtRD2GEHUaYCJgAepxrW1yDi3FJz2PAsMq9Rq8eDF14EykdDveGaQ5c4OmDDdPAwSvSaCXXC4W7DNgH3HVXD/2g40u2EhRJQ93VtsFWXlfJAjFgtye0dDRBXL9b38EcXS0IZfDpeIi19GjwJAcPUq2JHzdTxNcRlpvYjdvt9OMUewnf3FlFrd7DBvbOzpeQJmt7iMgvxc1O8nHlSOc1YovIbPjcJ7SE7QbTMs+qUb6v+WpVcnHkM6mLyj8BIiEOus+jfdm1N/HP973YFnLaVIgU+w/rXXiiGC8Kx5cWKHcGa4wFqurEKDPSawL/humImBtB5+H8isY0fMc71xRRDMsMEQRhMzfKek3ePszspZpQLujSCuQxajChzKTcmdos5fX8GcGMPfCTPNny2Wrx12QgrfVieYf2hkhqwpWfzDpUix12c9A+vXuYfPqMQpTaGC9VB76FqLmCUB3QO1nuAy0WuCQH1aPKJQiQ3D2xMwDceLKsBX6v69Ay9wWK/+x4hcxmhCHL/x61NgRMuO4U4YJ3YyV6NfAH9LOWTSChrivakY="
  - secure: "1VZOJlGLJR3CAQsBBa4rodWlhks1yDShSpIUmaiFv7nEvRWagt6waFPy/sc7DPDd3fyYiXsmGL0LQ/gZJyiJhFb6Yij3w+XKujvvzv3aKqZOuxDFCwQ2Dqzeunv21m57O6wq0MzYgZtW97ckLtbi8i5rAUsTayGBkLIMEd1/h39xWg/31u/xmP0j0+NdLZKIMNxMUKDioHYcKpZ8q2RXtFYEeaO5F6odbW6N1nZE6De5CSiZO59Zl61TY5Z3PGcTE0u3b43RrnAHvjNRwFftWIXq0uy6kE/wfVbuNBH2X1bvz9cnmnVVGk5yn6dPgbgBXgb8E+ts/M6IuEaVntMCKDiW3DA3qnI3kkx/sqPllVBG0tyc0nMgHVugYgzGX4DaAOORL3CZjslBvnNVA7LlGrBHbZb7l/h2e3lClp6fdX8EzFrvMzutIRUmwoHnssytFFH+sMMFWkopjQsj6HdvlcC++KQ5NGYg50myN2rO7SVuez3wFNPXidgQW7Q604cwSCKwIwh6sYboaesex4d1yL3xIJ/uGx7FuLF+ewZOS/D51H6qeVEXmtsGLx9TKBugLmgoPlGb89KY8LSTfvRIJgm9dwlyRJiYMptoCwmg5I4kuvlhDFFItP63CsmELjUhYUqkWaAY+JQsZp8oVbVXoseuI157VlaBqAFkPks6wCo="
