language: scala

sudo: false

scala:
- 2.12.12
- 2.13.3

jdk:
  - openjdk8

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++${TRAVIS_SCALA_VERSION}!" checkGenerate test
